services:
 app:
  build:
   context: ./server
   dockerfile: Dockerfile
  container_name: server
  ports:
   - "${PORT}:${PORT}"
  working_dir: /app
  volumes:
   - ./server:/app
  depends_on:
   postgres:
    condition: service_healthy
    restart: true
  environment:
   - PORT=${PORT}
   - DATABASE_URL=${DATABASE_URL}
  command: go run cmd/app/main.go

 postgres:
  image: postgres:15
  container_name: postgres
  restart: unless-stopped
  ports:
   - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  environment:
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  volumes:
   - postgres_data:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
   interval: 1s
   timeout: 10s
   retries: 5

volumes:
 postgres_data:
