# Logging Configuration
log_level: "debug"
log_format: "text"

# Feature Flags
enable_debug_endpoints: true
enable_metrics: false
enable_docs: true
allowed_methods: ["HEAD", "GET", "POST", "DELETE"]
allowed_origins: ["*"]
