# GoDoIt Server Configuration - Production
# Application-specific settings for production environment
# Deployment settings (port, database_url) are handled via environment variables

# Logging Configuration
log_level: "info"
log_format: "json"

# Feature Flags
enable_debug_endpoints: false
enable_metrics: false
enable_docs: true
allowed_origins: ["*"]
allowed_methods: ["HEAD", "GET", "POST", "DELETE"]
