// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Inbox struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PrivateKey string
	PublicKey  sql.NullString
	Active     bool
}

type Message struct {
	ID                int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	InboxID           int64
	MsgContent        string
	MsgFormat         string
	SentWithPublicKey bool
}
